export const GET_DOCTORS = 'GET_DOCTORS';
export const CLEAR_DOCTORS = 'CLEAR_DOCTORS';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const FILTER_DOCTORS = 'FILTER_DOCTORS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
